# Generated by Django 4.2.3 on 2023-10-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_owner_post_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.customer'),
        ),
    ]
